= Version Control in Git
:toc: left

Git is a version control system. It gives you a record of the history of your files and the changes you make to them. You can store just about any type of file in Git, but we'll see that it is particulary good at working with files that are written in plain text.

== Create an empty repository for your work

Create a folder to hold your work. Git refers to this folder as your **local repository.** This is a good chance to practice using the command line. 

.Windows
```
mkdir c://Users/<your-profile>/<my-repository>
```

.MacOS
```
mkdir ~/<my-repository>
```

Next, go to the directory you want to host your repository. The command line way to do this is:

`cd </path/to/directory>`

You can double-check that you are in the right place with the working directory command:

```
pwd
```

This should display your current location in the file tree. Once you are where you want to be, let's turn this folder into a Git repostitory:

```
git init
```

You should see some variation of the following message:

```
Initialized empty Git repository in /Users/ricklarsen/testdir/.git/
```

=== Git Status

Another safe command to run anytime is `git status` which just tells us about the state of our repository. Go ahead and run it now. 

```
git status
```

We haven't done anything yet, so we should get back something that looks like this:

```
On branch main

No commits yet

nothing to commit (create/copy files and use "git add" to track)
```

Git starts you with a default branch called `main`. A branch is an alternate version of your file set that you can safely make changes to and not update your original until you are sure you like those changes and want to keep them.

On the second line, because we have no commits yet we have no history to see.

The last line is Git trying to be helpful and tell you how to get started. Let's start making changes.

[NOTE]
====
If you get some form of the following error, you may need to check that you are in the correct folder:

```
fatal: not a git repository (or any of the parent directories): .git
```

If you are in the right place, just run `git init` again and then `git status` to check.
====

== Create a branch before starting work

It's a good practice to keep your `main` branch as clean as possible and only merge to it when you are satisfied with the state of any version. Git uses `branches` to keep those changes separate while they are in process. This way, you and any collaborators or team mates can work independently.

You can create multiple branches for different experiments, different tasks, or to keep different versions, if that's what you want. We'll start by focusing on short-lived branches that will be eventually merged and deleted.

=== Git checkout

To move between branches, you use the `git checkout` command. This command is usually safe to run, but you might want to run `git status` first as `git checkout` is also how you undo uncommitted changes, as we'll see later. 

We only have one branch so far, so we need to create one. We do this by adding a `-b` flag and giving our new branch a name. It's a good idea to use a meaningful name, especially if we're going to have more than a few eventually. Branch names can't have spaces, so let's call this one `test-branch`. The complete command should look close to this:

```
git checkout -b test-branch
```

Git confirms the new branch by telling us:

```
Switched to a new branch 'test-branch'
```

See all of your available branches:

```
git branch
```

This command returns:

```
  main
* test-branch
```

The asterisk (`*`) shows which is your current branch. To switch between the branches, run 

```
git checkout <branch-name>
```

Make sure you have the `test-branch` checked out and we can add files to our repository and then update them. 

== Add files to your repository

Now, you can go ahead and fill your new directory up with whatever files you want. For my example, I'll keep it simple and add only one or two files at a time to show you the Git workflow.

If you have some files you want to work with, great, or let's start with some more command line practice and learn about the `echo` command. 


```Bash
echo "sample text"
```

This command prints the text in quotations back to you in your terminal. Let's do something with that text now.

```
echo "sample text" >> .\sample_file01.txt
```

Now we've added the `>>` which redirects our output into the new file `sample_file01.txt`, which we can open in our favorite text editor. We should end up with the words "sample text" in a simple text file. That's good enough for now.

We now have an **untracked file** in our repository. That just means we haven't told Git to keep track of it yet. Let's ask Git about it.

```
On branch main

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.sample_file01.txt
```

=== Add a file to Staging

Git shows us the names of any untracked files in our repository, and it shows us how to add the file to Git: with the `git add` command. Let's try it out.

```
git add sample-file.txt
```

```
On branch test-branch
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   sample-file.txt
```

We haven't commited to our changes yet. Git gives you the chance to confirm that you only keep the changes you want to keep. It does this with an intermediary step called **Staging**. Prior to committing to changes, you "Stage" them, so you can look and make sure you are only adding the files you want to keep. 

We can also use `git restore --staged` if we want to back out and undo this step.

=== Commit a file

The last step now is to **Commit** our new file, using the `git commit` command. The `commit` command has an optional flag (`-m`) to let us commit the changes and write a **Commit message** in one step. Commit messages are helpful for reviewing history and it's important to be very descriptive with what you are changing and why. Your future self will thank you.

```
git commit -m "Added sample-file.txt to demonstrate committing changes"
```

Git returns a summary of what we have just committed, which should mostly match the following:

```
[test-branch 4a214e6eba] Added sample-file.txt to demonstrate committing changes
 1 file changed, 1 insertion(+)
 create mode 100644 sample-file.txt
```

Git confirms our branch (`test-branch`) and gives us a unique identifier (sometimes called a hash) for this specific commit (`4a214e6eba` in my example). Later, we can check out, or jump to, this exact spot in the history even after we make many more changes. We would use the `git checkout` command, but instead of a branch, we paste in that number:

```
git checkout 4a214e6eba
```

Also in the response is our commit message, a count of how many files we changed, and how many lines we added or deleted. So far, we have only added 1 file, and it only has one line in it (`1 insertion`).

The last line gives a breakdown of files created, modified, and deleted. We've only added one file, so we just have a `create mode` line for `sample-file.txt`.

== View history

We don't have a long history yet, but we can take a quick look at it to see our progress so far. The command to see the history of the current branch is `git log`.

```
git log
```

We only have one commit so far, and your name:

```
commit 4a214e6ebafa2f30d25a4466bb6fab2a5d7857a0 (HEAD -> test-branch)
Author: {your name} <{your email}>
Date:   {docdate}

    Added sample-file.txt to demonstrate committing changes
```

== Edit files

Now we can start to build some more history and experiment a little bit. Most of the commands are the same, but it's helpful to the different states your files can be in. 

Open your `sample-file.txt` in any text editor of your choice. You can make any changes you want: add or delete text and save your work when you are ready.

Now come back to the command line and check the status of your repository.

```
git status
```

We get back something like this:

```
On branch test-branch
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   sample-file.txt
```

It looks just like our previous message, excepte the file is now `modified` instead of `created`. 

At this step, we can even see everything that is changed with `git diff`:

```
git diff
```

After some internal information, we see a line-by-line report on the lines removed and lines added. Git doesn't directly report on lines changed, it sees an edit as removing the old line and adding a new one, even if you only change a single character.

```
-text
+textuality
```

Your console may color-code the deletes and additions, but also provides `-` and `+`. Also, if your "diff" gets very long, you can scroll through and may have to enter `q` to quit the diff viewer. 

Feel free to practice adding and editing more files before you commit. Just as before, you have several chances to check what you have changed before you commit. 

[WARNING]
====
This is one of the rare times you can lose work while working in Git. Git uses the `git checkout {FILENAME}` as an undo of unstaged changes, so be careful stage any changes you want to keep before using this command.
====

The following is a decent workflow to follow when you are ready to commit changes. Run these commands one at a time:

```
git status
git add {files or folders}
git status
git commit -m {message}
git status
git log
```

== Delete files

Deleting files is done is basically the same way. Git warns you if it detects files deleted as part of your change, so if you delete something you didn't mean to, you can restore it before you commit by using `git checkout {deleted-filename}`.

== Revert changes

If you do delete something you need to get back, you can run `git log` to find a previous commit that contained the file and check it out:

```
git checkout {commit hash}
```

You are no longer working on a branch, so Git gives you a lot of information here:

```
Note: switching to '4a214e6ebafa2f30d25a4466bb6fab2a5d7857a0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 4a214e6eba Added sample-file.txt to demonstrate committing changes
```
HEAD is an important concept referring to the most current commit you have checked out. Normally, HEAD is the most recent commit in your branch, but we are currently time-traveling to the past, so Git calls this a 'detached HEAD'. The rest of the statement is telling us we could create a new branch from here and ignore everything after. You might want to do that some day, but we just want to find our deleted file and get back to safety.

Find the file you want to restore and copy it somewhere safe, such as your Desktop or other folder outside of the Git repository. We'll return to our branch and copy it where we want it and then commit again.

== Files and folders

One thing to be aware of about working in Git is that it only tracks files and doesn't really understand folders. It keeps your folder structure, so feel free to organize your repository in a way that makes sense to you, but know that you can't commit an empty folder.

For example, if you have your files arranged like this example:

```
my-repo/
  section-1/
    page-01.txt
    page-02.txt
  section-2/
```

Git does not see the `section-2` folder until you add a file to it.

Also, when you create files in subfolders, `git status` shows the name of the top folder before the files are added to staging.

.Unstaged subfolders
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	section-1/
```

.Staged subfolders
```
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   section-1/page-1.txt
	new file:   section-1/page-2.txt
```

== Next Steps

Now you have enough commands to use Git on your own to track your own work and feel safe that you can experiment without overwriting your previous work. The real benefits of Git come from sharing changes with others, so we'll look at using Git collaboratively.

== Commands introduced

```
git init

git status

git branch

git checkout <branch>

git checkout -b <branch>

git add

git commit

git log

git diff

```
